// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQK_Bdq1ZkjIHr8wIPFPP7-C3HEpcW8Ac',
    appId: '1:723162991686:android:af664fbc87d29a8260ce47',
    messagingSenderId: '723162991686',
    projectId: 'falldetection-a2d3b',
    storageBucket: 'falldetection-a2d3b.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcE3_z1mkuSXHNobbOO-Iu94XYv4uudtI',
    appId: '1:723162991686:web:79ef991c539d5cb960ce47',
    messagingSenderId: '723162991686',
    projectId: 'falldetection-a2d3b',
    authDomain: 'falldetection-a2d3b.firebaseapp.com',
    storageBucket: 'falldetection-a2d3b.appspot.com',
    measurementId: 'G-0P9EP7BY44',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsa_Gy6-CJck7EYl-Zj181v4uzwG00Uas',
    appId: '1:723162991686:ios:ac17b287f898803660ce47',
    messagingSenderId: '723162991686',
    projectId: 'falldetection-a2d3b',
    storageBucket: 'falldetection-a2d3b.appspot.com',
    iosBundleId: 'com.example.falldetectionn1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsa_Gy6-CJck7EYl-Zj181v4uzwG00Uas',
    appId: '1:723162991686:ios:ac17b287f898803660ce47',
    messagingSenderId: '723162991686',
    projectId: 'falldetection-a2d3b',
    storageBucket: 'falldetection-a2d3b.appspot.com',
    iosBundleId: 'com.example.falldetectionn1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcE3_z1mkuSXHNobbOO-Iu94XYv4uudtI',
    appId: '1:723162991686:web:17f60cc1f212d33760ce47',
    messagingSenderId: '723162991686',
    projectId: 'falldetection-a2d3b',
    authDomain: 'falldetection-a2d3b.firebaseapp.com',
    storageBucket: 'falldetection-a2d3b.appspot.com',
    measurementId: 'G-3T2GM6ZRR2',
  );

}